# generated by datamodel-codegen:
#   filename:  tmpx95q_zyp.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class AcpEventModel(RootModel[Any]):
    root: Any = Field(..., title="AcpEventModel")


class State(Enum):
    """
    Current alarm state.
    """

    raised = "raised"
    cleared = "cleared"


class AlarmEvent(BaseModel):
    """
    X.733-aligned network alarm; carried on alarms.* topics.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    alarmId: str = Field(
        ..., description="Unique alarm identifier; idempotency key for alarm dedup."
    )
    managedObjectId: constr(
        pattern=r"^(Node|LineCard|Port|IPLink|IGPAdjacency|LSP|VPNService|FiberSpan|SRLG):[^:]+$"
    ) = Field(
        ...,
        description="Must match topology graph identity scheme '<objectType>:<id>'.",
        title="ManagedObjectId",
    )
    eventType: str = Field(..., description="X.733 event type.")
    probableCause: str = Field(..., description="X.733 probable cause.")
    perceivedSeverity: str = Field(..., description="X.733 severity.")
    raisedAt: AwareDatetime = Field(..., description="When the alarm was raised (ISO-8601 UTC).")
    clearedAt: AwareDatetime | None = Field(
        None, description="Set when the alarm is cleared (ISO-8601 UTC)."
    )
    state: State = Field(..., description="Current alarm state.")
    vendorRaw: dict[str, Any] | None = Field(
        None, description="Original vendor alarm payload, pass-through."
    )
    trailIds: list[str] = Field(
        ..., description="Populated by Enrichment Service; empty before enrichment."
    )


class TopologyChangedEvent(BaseModel):
    """
    Carried on topology.changed; emitted by the Topology Service.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    snapshotId: str = Field(..., description="Identifies the topology snapshot version.")
    changeType: str = Field(..., description="Describes the nature of the topology change.")
    nodes: list[dict[str, Any]] = Field(..., description="Typed node descriptors.")
    edges: list[dict[str, Any]] = Field(..., description="Typed edge descriptors.")


class TrailsBuiltEvent(BaseModel):
    """
    Carried on trails.built. Summary only; full membership fetched via the Trail Builder API.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    snapshotId: str = Field(..., description="Topology snapshot this build references.")
    trailIds: list[str] = Field(
        ..., description="Array of trail identifiers built in this snapshot."
    )
    trailCount: int = Field(..., description="Number of trails built (must equal trailIds.length).")


class CodebookGeneratedEvent(BaseModel):
    """
    Carried on codebook.generated. Summary only; full signatures fetched via the Codebook Generator API.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    snapshotId: str = Field(..., description="Topology snapshot this codebook was compiled from.")
    scenarioCount: int = Field(..., description="Number of scenarios in this codebook.")
    codebookId: str = Field(
        ...,
        description="Identifies this codebook version; referenced as matchedCodebookId in CorrelationResultEvent.",
    )


class TransactionEvent(BaseModel):
    """
    Carried on transactions.clean. Raw DBSCAN-cleaned, trail-scoped alarm groups from the Noise Filter.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    transactionId: str = Field(..., description="Unique identifier for this transaction group.")
    trailId: str = Field(..., description="Trail scope of the alarm group.")
    snapshotId: str = Field(
        ..., description="Topology snapshot in scope when this group was formed."
    )
    alarmIds: list[str] = Field(..., description="Alarm identifiers in this DBSCAN-cleaned group.")
    windowStart: AwareDatetime = Field(
        ..., description="Start of the raw time window (ISO-8601 UTC)."
    )
    windowEnd: AwareDatetime = Field(..., description="End of the raw time window (ISO-8601 UTC).")


class Provenance(BaseModel):
    """
    Mining provenance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    sourceWindowId: str = Field(
        ..., description="Identifies the transaction window this pattern was mined from."
    )
    snapshotId: str = Field(..., description="Topology snapshot version in scope when mining ran.")
    codebookVersion: str = Field(..., description="Codebook version in scope when mining ran.")


class PatternMinedEvent(BaseModel):
    """
    Carried on patterns.mined; Pattern Miner output only. Deliberately carries NO rootCauseAlarmType, lifecycle, or patternId field (RCA and lifecycle belong to the Pattern Manager).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    sequence: list[str] = Field(..., description="Ordered alarm type sequence discovered.")
    support: float = Field(..., description="Frequency of the sequence.")
    confidence: float = Field(..., description="Conditional probability.")
    lift: float = Field(..., description="Lift over baseline.")
    trailId: str = Field(
        ..., description="Trail scope the pattern was mined from (top-level field)."
    )
    timing: dict[str, Any] = Field(
        ..., description="Inter-arrival timing statistics for the sequence."
    )
    provenance: Provenance = Field(..., description="Mining provenance.")


class PatternDiscoveredEvent(BaseModel):
    """
    Carried on patterns.discovered; Pattern Manager output.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    patternId: str = Field(..., description="Stable identifier assigned by Pattern Manager.")
    sequence: list[str] = Field(..., description="Ordered alarm type sequence.")
    rootCauseAlarmType: str = Field(..., description="Alarm type tagged as root cause.")
    support: float
    confidence: float
    lift: float
    timing: dict[str, Any] = Field(..., description="Timing statistics.")
    codebookMatchId: str | None = Field(None, description="Matched codebook scenario, if any.")
    lifecycle: str = Field(..., description="Pattern lifecycle state (e.g. draft).")


class PatternApprovedEvent(BaseModel):
    """
    Carried on patterns.approved; Pattern Manager output after human approval.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    patternId: str
    sequence: list[str] = Field(..., description="Ordered alarm type sequence.")
    rootCauseAlarmType: str = Field(..., description="Alarm type tagged as root cause.")
    support: float
    confidence: float
    lift: float
    timing: dict[str, Any] = Field(..., description="Timing statistics.")
    codebookMatchId: str | None = Field(None, description="Matched codebook scenario, if any.")
    lifecycle: str = Field(..., description="'approved' at the point this event is emitted.")


class CorrelationResultEvent(BaseModel):
    """
    Carried on correlation.results; Correlation Engine output.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    incidentId: str = Field(..., description="Unique incident identifier.")
    rootCauseAlarmId: str = Field(..., description="alarmId of the tagged root-cause alarm.")
    childAlarmIds: list[str] = Field(..., description="alarmIds of correlated child alarms.")
    matchedPatternId: str | None = Field(None, description="Pattern that matched, if any.")
    matchedCodebookId: str | None = Field(
        None,
        description="Codebook scenario that matched, if any; references codebookId from CodebookGeneratedEvent.",
    )
    confidence: float = Field(..., description="Correlation confidence score.")
    trailId: str = Field(..., description="Trail scope of the incident.")


class KnowledgeUpdatedEvent(BaseModel):
    """
    Carried on knowledge.updated. Minimal refresh trigger emitted by the Knowledge Service so consumers know WHAT changed and re-fetch the specific version via the Knowledge API; the knowledge itself lives in the versioned store/API, not in the event.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    recordType: str = Field(
        ...,
        description="Which kind of knowledge record changed; free-form per the domain-template model (e.g. propagationTemplate, faultOriginType, trailPolicy, modelParams).",
    )
    recordId: str | None = Field(
        None,
        description="Identifier of the specific record that changed; absent implies a broader change of that recordType.",
    )
    version: str = Field(
        ...,
        description="The new version of the changed knowledge; consumers fetch this version via the Knowledge API.",
    )
    domain: str = Field(
        ...,
        description="The domain scope (e.g. core-ip), per the platform's domain-extensibility model.",
    )


class Type(Enum):
    """
    Discriminator; maps 1:1 to a payload schema.
    """

    AlarmEvent = "AlarmEvent"
    TopologyChangedEvent = "TopologyChangedEvent"
    TrailsBuiltEvent = "TrailsBuiltEvent"
    CodebookGeneratedEvent = "CodebookGeneratedEvent"
    TransactionEvent = "TransactionEvent"
    PatternMinedEvent = "PatternMinedEvent"
    PatternDiscoveredEvent = "PatternDiscoveredEvent"
    PatternApprovedEvent = "PatternApprovedEvent"
    CorrelationResultEvent = "CorrelationResultEvent"
    KnowledgeUpdatedEvent = "KnowledgeUpdatedEvent"


class Envelope(BaseModel):
    """
    Canonical event envelope. 'type' discriminates 'payload' to exactly one of the nine payload schemas. schemaVersion major must equal the supported major (1); consumers reject >= 2.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    eventId: UUID = Field(..., description="Globally unique per event; idempotency key.")
    type: Type = Field(..., description="Discriminator; maps 1:1 to a payload schema.")
    schemaVersion: int = Field(..., description="Initial value 1; consumers accept 1, reject >= 2.")
    occurredAt: AwareDatetime = Field(..., description="When the event occurred (ISO-8601 UTC).")
    source: str = Field(..., description="Originating service name.")
    traceId: str = Field(..., description="Distributed trace identifier.")
    payload: dict[str, Any] = Field(
        ..., description="Typed per 'type'; one of the nine payload schemas."
    )
