"""FastAPI read-only surface — /health, /metrics, /labels, /scenarios (criteria 10, 10a, 16, 17).

A small read-only HTTP surface for ground-truth retrieval + liveness/metrics. OpenAPI 3.1 is
auto-generated by FastAPI at ``/openapi.json`` (the checked-in ``openapi.json`` is the
authoritative surface). ``/labels`` returns the frozen shape
``{scenarioId, scenarioType, rootCause, rootCauseManagedObjectId, rootCauseAlarmType, children[]}``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel

from simulator.engine.labels import LabelStore
from simulator.obs import metrics
from simulator.synth.p3_labels import P3LabelStore


@dataclass
class RunState:
    """Shared service state the HTTP surface reads (liveness + ground-truth index)."""

    started: bool = False
    kafka_connected: bool = True
    run_id: str | None = None
    labels: LabelStore = field(default_factory=LabelStore)
    scenarios: list[dict[str, object]] = field(default_factory=list)
    p3_labels: P3LabelStore = field(default_factory=P3LabelStore)

    @property
    def healthy(self) -> bool:
        return self.started and self.kafka_connected


class GroundTruthLabelModel(BaseModel):
    """Frozen /labels response shape."""

    scenarioId: str
    scenarioType: str
    rootCause: str
    rootCauseManagedObjectId: str
    rootCauseAlarmType: str
    children: list[str]


class P3CascadeLabelModel(BaseModel):
    """Additive /labels record for P3 synth cascades (same endpoint, additive fields).

    ``instanceIndex``/``igpArea`` are additive network-wide fields (AC 54); defaulted so existing
    single-trail consumers are unaffected.
    """

    patternId: str
    trailId: str
    rootCauseAlarmId: str
    rootCauseAlarmType: str
    childAlarmIds: list[str]
    scenarioType: str
    instanceIndex: int = 1
    igpArea: str | None = None


class P3RunSummaryModel(BaseModel):
    """/labels/p3-summary response — the run summary; the 60-70% KPI is directly computable.

    Network-wide adds the spread + enrichment fields (all additive, defaulted): distinct trails/
    areas used (AC 53), shortfall cascades (AC 55), enrichmentSafeCount + enrichmentConflictPatterns
    (AC 51/65), and the over-provisioned emitted fraction (AC 51).
    """

    totalAlarms: int
    alignedAlarms: int
    nonAlignedAlarms: int
    alignedFraction: float
    distinctTrailsUsed: int = 0
    distinctAreasUsed: int = 0
    shortfallCascades: int = 0
    enrichmentSafeCount: int = 0
    enrichmentConflictPatterns: list[str] = []
    alignedFractionEmitted: float = 0.0


class HealthModel(BaseModel):
    status: str
    kafka: str
    run: str


def create_app(state: RunState) -> FastAPI:
    """Build the FastAPI app bound to a shared :class:`RunState`."""
    app = FastAPI(title="ACP Simulator", version="0.1.0")

    @app.get("/health", response_model=HealthModel)
    def health() -> Response:
        body = HealthModel(
            status="ok" if state.healthy else "unhealthy",
            kafka="connected" if state.kafka_connected else "disconnected",
            run=state.run_id or "idle",
        )
        status_code = 200 if state.healthy else 503
        return Response(
            content=body.model_dump_json(),
            media_type="application/json",
            status_code=status_code,
        )

    @app.get("/metrics")
    def metrics_endpoint() -> Response:
        return Response(content=metrics.render(), media_type="text/plain; version=0.0.4")

    @app.get(
        "/labels",
        response_model=list[GroundTruthLabelModel | P3CascadeLabelModel],
    )
    def labels(scenarioId: str | None = None) -> list[dict[str, object]]:
        if scenarioId is not None:
            label = state.labels.get(scenarioId)
            if label is None:
                raise HTTPException(status_code=404, detail=f"unknown scenarioId {scenarioId}")
            from simulator.engine.labels import label_to_dict

            return [label_to_dict(label)]
        # Generate/ingest scenario labels + (additive) P3 synth cascade labels on the same surface.
        return state.labels.to_dicts() + state.p3_labels.to_dicts()

    @app.get("/labels/p3-summary", response_model=P3RunSummaryModel)
    def p3_summary() -> dict[str, object]:
        summary = state.p3_labels.summary
        if summary is None and state.p3_labels.all():
            summary = state.p3_labels.compute_summary()
        if summary is None:
            raise HTTPException(status_code=404, detail="no P3 synth run recorded")
        return summary.to_json()

    @app.get("/labels/{scenario_id}", response_model=GroundTruthLabelModel)
    def label_by_id(scenario_id: str) -> dict[str, object]:
        label = state.labels.get(scenario_id)
        if label is None:
            raise HTTPException(status_code=404, detail=f"unknown scenarioId {scenario_id}")
        from simulator.engine.labels import label_to_dict

        return label_to_dict(label)

    @app.get("/scenarios")
    def scenarios() -> list[dict[str, object]]:
        return state.scenarios

    return app
