"""FastAPI read-only surface — /health, /metrics, /labels, /scenarios (criteria 10, 10a, 16, 17).

A small read-only HTTP surface for ground-truth retrieval + liveness/metrics. OpenAPI 3.1 is
auto-generated by FastAPI at ``/openapi.json`` (the checked-in ``openapi.json`` is the
authoritative surface). ``/labels`` returns the frozen shape
``{scenarioId, scenarioType, rootCause, rootCauseManagedObjectId, rootCauseAlarmType, children[]}``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel

from simulator.engine.labels import LabelStore
from simulator.obs import metrics


@dataclass
class RunState:
    """Shared service state the HTTP surface reads (liveness + ground-truth index)."""

    started: bool = False
    kafka_connected: bool = True
    run_id: str | None = None
    labels: LabelStore = field(default_factory=LabelStore)
    scenarios: list[dict[str, object]] = field(default_factory=list)

    @property
    def healthy(self) -> bool:
        return self.started and self.kafka_connected


class GroundTruthLabelModel(BaseModel):
    """Frozen /labels response shape."""

    scenarioId: str
    scenarioType: str
    rootCause: str
    rootCauseManagedObjectId: str
    rootCauseAlarmType: str
    children: list[str]


class HealthModel(BaseModel):
    status: str
    kafka: str
    run: str


def create_app(state: RunState) -> FastAPI:
    """Build the FastAPI app bound to a shared :class:`RunState`."""
    app = FastAPI(title="ACP Simulator", version="0.1.0")

    @app.get("/health", response_model=HealthModel)
    def health() -> Response:
        body = HealthModel(
            status="ok" if state.healthy else "unhealthy",
            kafka="connected" if state.kafka_connected else "disconnected",
            run=state.run_id or "idle",
        )
        status_code = 200 if state.healthy else 503
        return Response(
            content=body.model_dump_json(),
            media_type="application/json",
            status_code=status_code,
        )

    @app.get("/metrics")
    def metrics_endpoint() -> Response:
        return Response(content=metrics.render(), media_type="text/plain; version=0.0.4")

    @app.get("/labels", response_model=list[GroundTruthLabelModel])
    def labels(scenarioId: str | None = None) -> list[dict[str, object]]:
        if scenarioId is not None:
            label = state.labels.get(scenarioId)
            if label is None:
                raise HTTPException(status_code=404, detail=f"unknown scenarioId {scenarioId}")
            from simulator.engine.labels import label_to_dict

            return [label_to_dict(label)]
        return state.labels.to_dicts()

    @app.get("/labels/{scenario_id}", response_model=GroundTruthLabelModel)
    def label_by_id(scenario_id: str) -> dict[str, object]:
        label = state.labels.get(scenario_id)
        if label is None:
            raise HTTPException(status_code=404, detail=f"unknown scenarioId {scenario_id}")
        from simulator.engine.labels import label_to_dict

        return label_to_dict(label)

    @app.get("/scenarios")
    def scenarios() -> list[dict[str, object]]:
        return state.scenarios

    return app
